- id: '1741548057571'
  alias: AI Event Summary (v1.4.0)
  description: ''
  use_blueprint:
    path: valentinfrlch/event_summary_beta.yaml
    input:
      important: true
      remember: true
      use_memory: true
      notify_device:
      - 580dd20cc37be2949464dfcce9e43e2b
      camera_entities:
      - camera.back_door_doorbell
      - camera.barn_door_camera
      - camera.front_door_doorbell
      - camera.front_yard_camera
      - camera.garden_camera
      provider: 01JJ2MEBJEPG68GPS79VSSTDSX
      model: llama3.2
- id: '1741565087721'
  alias: Analyze Garden Movement
  description: ''
  use_blueprint:
    path: valentinfrlch/event_summary_beta.yaml
    input:
      remember: true
      notify_device:
      - 580dd20cc37be2949464dfcce9e43e2b
      camera_entities:
      - camera.garden_camera
      motion_sensors:
      - binary_sensor.garden_sensor_occupancy
      provider: 01JJ2N0R9M8KKY45WNMFAA5W01
      model: llama3.2
      important: true
      message: 'Summarize the events based on a series of images captured at short
        intervals. Focus only on moving subjects such as people, animals. Ignore static
        objects and scenery. Provide a clear and concise account of movements and
        interactions. Do not mention or imply the existence of images—present the
        information as if directly observing the events. If no movement is detected,
        respond with: ''No activity observed.'''
      tap_navigate: /lovelace/camera-events/0
