
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  # Name of the location where Home Assistant is running
  name: 5767 Nina Cir
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude 
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 82
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  country: US
  # packages: !include_dir_named packages
  # external_url: !secret  tts_base_url

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
input_boolean: !include_dir_merge_named input_booleans
scene: !include scenes.yaml
group: !include_dir_merge_named groups