- platform: template
  sensors:
    girls_home:
      unique_id: 23c097c4-cf57-4b5e-8995-4fbfa3593758
      friendly_name: Girls Home
      value_template: >-
        {{ is_state('person.camdyn_frey', 'home') or is_state('person.molly_frey', 'home') }}
