- platform: template
  sensors:
    we_are_out_of_bed:
      friendly_name: We are out of bed
      value_template: >
        {{ is_state('binary_sensor.sleepnumber_our_bed_daniel_is_in_bed', 'off')  and is_state('binary_sensor.sleepnumber_our_bed_stephanie_is_in_bed', 'off') }}
