automation:
  - id: 'd3cfe7e4-6a8d-48e4-bbcd-1891f303339f'
    alias: "It's time to workout"
    description: ""
    trigger:
      - platform: time
        at: "05:40:00"
    condition: []
    action:
      - service: light.turn_on
        target:
          area_id: basement
        data: 
          brightness_pct: 100
    mode: single

  - id: '92bb115c-a192-40bc-9e0d-0443787cab0f'
    alias: "Workout is done"
    description: ""
    mode: single
    trigger:
      - platform: time
        at: "08:30:00"
    condition: []
    action:
      - service: light.turn_off
        target:
          area_id: basement
        data: {}

  - id: '6d4a7378-2e8c-4c3a-817a-6328bb8de01a'
    alias: "Basement Light Switch Automation"
    description: "Turn the Basement Lights On or Off"
    trigger:
      - platform: state
        entity_id: switch.basement_light_switch
    condition: []
    action:
      - service: "light.turn_{{ trigger.to_state.state }}"
        target:
          area_id: basement
        data: {}
