automation:

  - id: '9d331eec-830d-4e25-bfc3-06facbfd28f0'
    alias: "Routine | Bathroom | Wake Up"
    description: "Turn on Bathroom Lights if it's a School Day and not a Holiday or Snow Day"
    mode: queued
    max: 10
    trigger:
      - platform: time
        at: "05:45:00"
    condition:
      - condition: state
        entity_id: binary_sensor.school_day
        state: "on"
      - condition: not
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.holiday
                state: "on"
              - condition: state
                entity_id: binary_sensor.snow_day
                state: "on"
    action:
      - service: light.turn_on
        data:
          transition: 300
          color_temp_kelvin: 2700
          brightness_pct: 30
        target:
          area_id: &areas
            - bathroom

  - id: 'b7d8f59b-f3b2-4ddb-973e-76c474bff574'
    alias: "Routine | Bathroom | Away"
    description: "Turn off the bathroom lights when the girls are away"
    mode: single
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.girls_home
      from: "on"
      to: "off"
      for:
        minutes: 5
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 2
        target: 
          area_id: *areas
