automation:
  - id: 'f3bf4eac-01a4-46a8-bd3f-f580fba80cc5'
    alias: "Camdyn is at school"
    description: "She arrived at school, turn off the lights"
    mode: single
    trigger:
      - platform: zone
        entity_id: person.camdyn_frey
        zone: zone.southern_lehigh_high_school
        event: enter
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: camdyn_s_room
