automation:
  
  - id: 'dde44bf2-bf0d-4d46-8a3e-b74ea8c59564'
    alias: "Routine | Camdyn's Room | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition:
      - condition: zone
        entity_id: person.camdyn_frey
        zone: zone.home
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - camdyn_s_room

  - id: 'bee92ca7-72cd-4b90-9e77-1d92960bc1f9'
    alias: "Routine | Camdyn's Room | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition:
      - condition: zone
        entity_id: person.camdyn_frey
        zone: zone.home
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - camdyn_s_room
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: 'f3bf4eac-01a4-46a8-bd3f-f580fba80cc5'
    alias: "Routine | Camdyn's Room | Away"
    description: "Turn off Camdyn's Room Lights when she is not at home"
    mode: single
    trigger:
      - platform: zone
        entity_id: person.camdyn_frey
        zone: zone.home
        event: leave
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: camdyn_s_room

  - id: '53af2938-b66c-4226-a5e2-ac4bb455649e'
    alias: "Routine | Camdyn's Room | Arrive Home"
    description: "Turn on Camdyn's Room Lights when she arrives home and it's after sunset"
    mode: single
    trigger:
      - platform: zone
        entity_id: person.camdyn_frey
        zone: zone.home
        event: enter
    condition:
      - condition: sun
        after: sunset
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 75
        target:
          area_id: camdyn_s_room
