automation:

  - id: 'aa2c400f-30b1-45ac-bb86-dfc7aa49f991'
    alias: "Routine | Den | Sunrise"
    description: "Turn off the lights 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition: []
    action:
      - service: light.turn_off
        data:
          transition: 2
        target:
          area_id: &areas
            - den

  - id: 'b7b19a14-efe6-48ef-b257-1a1d8478b6b6'
    alias: "Routine | Den | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id: *areas

  - id: 'f0563edc-f36c-4c35-9ad3-6b7c55bfdfa6'
    alias: "Routine | Den | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60
        target:
          area_id: *areas
