automation:

  - id: '3f4c0fdf-d9ef-468e-a973-8e7fa82c7483'
    alias: "Routine | Family Room | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - family_room
            - family_room_ambient

  - id: 'a85932d9-ff4e-486b-a3a1-89b07e84feef'
    alias: "Routine | Family Room | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - family_room
            - family_room_ambient
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

