automation:

  - id: 'bd94adbb-6d48-41e8-ba41-deb8f9538bd5'
    alias: "Routine | Family Room | Sunrise"
    description: "Turn off the lights 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition: []
    action:
      - service: light.turn_off
        data:
          transition: 2
        target:
          area_id: &areas
            - family_room
            # - family_room_ambient

  - id: '3f4c0fdf-d9ef-468e-a973-8e7fa82c7483'
    alias: "Routine | Family Room | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id: *areas

  - id: 'a85932d9-ff4e-486b-a3a1-89b07e84feef'
    alias: "Routine | Family Room | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60
        target:
          area_id: *areas

  - id: '7c7bcd97-f955-4f9d-b85b-7fb36a0ff198'
    alias: "Routine | Family Room | Away"
    description: "Everyone has left the house, turn off the Family Room Lights if the time is before sunset"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.family_home
        from: "on"
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: sun
        before: sunset
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 2
        target:
          area_id: *areas
      - service: switch.turn_off
        metadata: {}
        data: {}
        target:
          area_id:
            - family_room
            - family_room_ambient
