automation:
  - id: '33054812-ad0f-4412-af49-9aae78c484bd'
    alias: 'Routine | Sunset | Firepit'
    description: "Firepit Lights turn on or off"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - platform: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
    condition: []
    action:
      - choose:
          
          - conditions:
              - condition: trigger
                id:
                  - just_before_sunset
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.barn_door_light

          - conditions:
              - alias: It's just before sunset and there is no custom schedule set
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "false"
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.barn_door_light
          
          - conditions:
              - alias: It's just before sunset and its Valentine's Day
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.valentine
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Romantic: Ruby romance'

          - conditions:
              - alias: It's just before sunset and it's the Fall Season
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.fall
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'
          
          - conditions:
              - alias: It's just before sunset and it's Halloween
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.halloween
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Halloween: Trick or treat'
          
          - conditions:
              - alias: It's just before sunset and it's the Winter Season
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.winter
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Snow sparkle'
          
          - conditions:
              - alias: It's just before sunset and it's Christmas
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.christmas
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Under the tree'

          - conditions:
              - alias: It's just before sunset and the Flyers are on
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.flyers
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'        

          - conditions:
            - alias: It's just before sunset and the Eagles are on
              condition: and
              conditions:
                - condition: trigger
                  id:
                    - just_before_sunset
                - condition: state
                  entity_id: binary_sensor.eagles
                  state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'        
                            
          - conditions:
            - alias: It's just before sunset and the Phillies are on
              condition: and
              conditions:
                - condition: trigger
                  id:
                    - just_before_sunset
                - condition: state
                  entity_id: binary_sensor.phillies
                  state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'        
        
          - conditions:
            - alias: It's just before sunset and Penn St is on
              condition: and
              conditions:
                - condition: trigger
                  id:
                    - just_before_sunset
                - condition: state
                  entity_id: binary_sensor.penn_st
                  state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'        


          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.barn_door_light
