automation:
  - id: '33054812-ad0f-4412-af49-9aae78c484bd'
    alias: 'Routine | Firepit | Sunset'
    description: "Firepit Lights turn on or off"
    mode: single
    trigger:
      - trigger: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - trigger: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
      - trigger: state
        entity_id:
          - input_boolean.light_reset
        to: "on"
        id: light_reset
    condition: []
    action:
      - choose:
          
          - conditions:
              - alias: It's just before sunset or light reset and there is no custom schedule set
                and:
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "False"
                  - or:
                    - condition: trigger
                      id:
                        - just_before_sunset
                    - condition: trigger
                      id:
                        - light_reset
            sequence:
              - service: light.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - light.barn_door_light
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 30
                  milliseconds: 0
              - service: light.turn_on
                metadata: {}
                data:
                  color_temp_kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.barn_door_light

          - conditions:
              - alias: It's just before sunset or light reset and a custom light schedule is set
                and:
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "True"
                  - or:
                    - condition: trigger
                      id:
                        - just_before_sunset
                    - condition: trigger
                      id:
                        - light_reset
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.firepit_custom_light_scene
                data:
                  variables:
                    scene: |
                      {% if has_value('input_select.custom_light_scene_selections') %}
                        {{ states('input_select.custom_light_scene_selections') }}
                      {% else %}
                        Savanna sunset
                      {% endif %}
                    repeat_delay:
                      hours: 0
                      minutes: 0
                      seconds: 30
                    onlyonlights: false
                    use_scene_brightness: false
                    brightness: 100

          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.barn_door_light
      
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
      
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.light_reset
