automation:

  - id: '4db8efe1-3370-499b-b5e6-e3ed4d7a304c'
    alias: "Routine | Foyer | Sunrise"
    description: "Turn off the lights 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:45:00"
    condition: []
    action:
      - service: light.turn_off
        data:
          transition: 2
        target:
          area_id: &areas
            - foyer

  - id: 'e5f16484-525e-4e1f-92fc-b73cf9cab8f2'
    alias: "Routine | Foyer | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id: *areas

  - id: 'cf9c7092-2806-48e7-b4e7-dfb20e8fb3e0'
    alias: "Routine | Foyer | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60
        target:
          area_id: *areas
