automation:
  - id: 'fb86e6f6-e22e-447b-b32f-18bd71266a24'
    alias: 'Routine | Front Yard | Sunset'
    description: "Front Yard Lights turn on or off"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - platform: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
    condition: []
    action:
      - choose:
          
          - conditions:
              - alias: It's just before sunset and there is no custom schedule set
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "false"
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.front_yard_bollard_1
                    - light.front_yard_bollard_2
                    - light.front_yard_bollard_3
                    - light.front_yard_bollard_4
                    - light.front_yard_spot_1
                    - light.front_yard_spot_2
          
          - conditions:
              - alias: It's just before sunset and its Valentine's Day
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.valentine
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: 'Romantic: Ruby romance'

          - conditions:
              - alias: It's just before sunset and it's the Fall Season
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.fall
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: 'Pure: Autumn gold'
          
          - conditions:
              - alias: It's just before sunset and it's Halloween
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.halloween
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: 'Halloween: Trick or treat'
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_holiday_custom_light_scene
                data:
                  variables:
                    scene: 'Halloween: Trick or treat'
          
          - conditions:
              - alias: It's just before sunset and it's the Winter Season
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.winter
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Snow sparkle'
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_holiday_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Snow sparkle'
          
          - conditions:
              - alias: It's just before sunset and it's Christmas
                condition: and
                conditions:
                  - condition: trigger
                    id:
                      - just_before_sunset
                  - condition: state
                    entity_id: binary_sensor.christmas
                    state: "true"
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Under the tree'
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_holiday_custom_light_scene
                data:
                  variables:
                    scene: 'Winter holidays: Under the tree'
          
          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_bollard_1
                    - light.front_yard_bollard_2
                    - light.front_yard_bollard_3
                    - light.front_yard_bollard_4
                    - light.front_yard_spot_1
                    - light.front_yard_spot_2
                    - light.front_yard_festiva_1
                    - light.front_yard_festiva_2

  - id: 'ecf2ed39-f371-4d3b-812d-2a4b3dc4992d'
    alias: 'Routine | Security Lights | Front Yard'
    description: "Front Yard Security Lights turn on or off"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - platform: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - just_before_sunset
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  brightness_pct: 70
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2

  - id: '0743426e-a630-48af-9d91-9728e3ecfff7'
    alias: 'Motion Sensor | Security Lights | Front Yard'
    description: "Front Yard Security Lights Automations"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.front_yard_sensor_occupancy
        to: "on"
        id: front_yard_sensor_motion_detected
      - platform: state
        entity_id:
          - binary_sensor.front_yard_sensor_occupancy
        to: "off"
        for:
          hours: 0
          minutes: 10
          seconds: 0
        id: front_yard_sensor_area_cleared
    condition:
      condition: or
      conditions:      
        - condition: time
          after: "23:00:00"
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
        - condition: sun
          before: sunrise
          before_offset: '00:15:00'
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - front_yard_sensor_motion_detected
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  brightness_pct: 50
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - front_yard_sensor_area_cleared
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
