automation:
  - id: 'fb86e6f6-e22e-447b-b32f-18bd71266a24'
    alias: 'Routine | Front Yard | Sunset'
    description: "Front Yard Lights turn on or off"
    mode: single
    trigger:
      - trigger: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - trigger: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
      - trigger: state
        entity_id:
          - input_boolean.light_reset
        to: "on"
        id: light_reset
    condition: []
    action:
      - choose:
          
          - conditions:
              - alias: It's just before sunset or light reset and there is no custom schedule set
                and:
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "False"
                  - or:
                    - condition: trigger
                      id:
                        - just_before_sunset
                    - condition: trigger
                      id:
                        - light_reset
            sequence:
              - service: light.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - light.front_yard_bollard_1
                    - light.front_yard_bollard_2
                    - light.front_yard_bollard_3
                    - light.front_yard_bollard_4
                    - light.front_yard_spot_1
                    - light.front_yard_spot_2
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 5
                  milliseconds: 0
              - service: light.turn_on
                metadata: {}
                data:
                  color_temp_kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id:
                    - light.front_yard_bollard_1
                    - light.front_yard_bollard_2
                    - light.front_yard_bollard_3
                    - light.front_yard_bollard_4
                    - light.front_yard_spot_1
                    - light.front_yard_spot_2

          - conditions:
              - alias: It's just before sunset or light reset and a custom light schedule is set
                and:
                  - condition: state
                    entity_id: sensor.custom_light_schedule
                    state: "True"
                  - or:
                    - condition: trigger
                      id:
                        - just_before_sunset
                    - condition: trigger
                      id:
                        - light_reset
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_custom_light_scene
                data:
                  variables:
                    scene: |
                      {% if has_value('input_select.custom_light_scene_selections') %}
                        {{ states('input_select.custom_light_scene_selections') }}
                      {% else %}
                        Savanna sunset
                      {% endif %}
                    repeat_delay:
                      hours: 0
                      minutes: 0
                      seconds: 30
                    onlyonlights: false
                    use_scene_brightness: false
                    brightness: 100

              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.winter
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.christmas_eve
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.christmas_day
                    state: "on"
              - action: light.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id:
                    - light.front_yard_christmas_lights
                    - light.front_yard_christmas_tree_light
                    - light.tp_link_smart_plug_8d86_garage_christmas_lights_1
                    - light.tp_link_smart_plug_8d86_garage_christmas_lights_2
                    - light.tp_link_smart_plug_938d_living_room_christmas_lights_1
                    - light.tp_link_smart_plug_938d_living_room_christmas_lights_2
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id: script.front_yard_holiday_custom_light_scene
                data:
                  variables:
                    scene: >
                      {% if has_value('input_select.custom_light_scene_selections') %}
                        {{ states('input_select.custom_light_scene_selections') }}
                      {% else %}
                        Savanna sunset
                      {% endif %}
                    repeat_delay:
                      hours: 0
                      minutes: 0
                      seconds: 30
                    onlyonlights: false
                    use_scene_brightness: false
                    brightness: 100

          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_bollard_1
                    - light.front_yard_bollard_2
                    - light.front_yard_bollard_3
                    - light.front_yard_bollard_4
                    - light.front_yard_spot_1
                    - light.front_yard_spot_2
                    - light.front_yard_christmas_lights
                    - light.front_yard_christmas_tree_light
                    - light.tp_link_smart_plug_8d86_garage_christmas_lights_1
                    - light.tp_link_smart_plug_8d86_garage_christmas_lights_2
                    - light.tp_link_smart_plug_938d_living_room_christmas_lights_1
                    - light.tp_link_smart_plug_938d_living_room_christmas_lights_2
                    - light.front_yard_festiva_1
                    - light.front_yard_festiva_2
      
      - delay:
          hours: 0
          minutes: 0
          seconds: 30
          milliseconds: 0
      
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.light_reset

  - id: 'ecf2ed39-f371-4d3b-812d-2a4b3dc4992d'
    alias: 'Routine | Security Lights | Front Yard'
    description: "Front Yard Security Lights turn on or off"
    mode: single
    trigger:
      - trigger: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - trigger: sun
        event: sunrise
        offset: "00:20:00"
        id: just_after_sunrise
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - just_before_sunset
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  brightness_pct: 70
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - just_after_sunrise
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2

  - id: '0743426e-a630-48af-9d91-9728e3ecfff7'
    alias: 'Motion Sensor | Security Lights | Front Yard'
    description: "Front Yard Security Lights Automations"
    mode: single
    trigger:
      - trigger: state
        entity_id:
          - binary_sensor.front_yard_sensor_occupancy
        to: "on"
        id: front_yard_sensor_motion_detected
      - trigger: state
        entity_id:
          - binary_sensor.front_yard_sensor_occupancy
        to: "off"
        for:
          hours: 0
          minutes: 10
          seconds: 0
        id: front_yard_sensor_area_cleared
    condition:
      condition: or
      conditions:      
        - condition: time
          after: "23:00:00"
          weekday:
            - sun
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
        - condition: sun
          before: sunrise
          before_offset: '00:15:00'
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - front_yard_sensor_motion_detected
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  brightness_pct: 50
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - front_yard_sensor_area_cleared
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.front_yard_security_light_1
                    - light.front_yard_security_light_2
