automation:
  - id: '3d9f5be1-782c-4194-a13a-d25ab0477e11'
    alias: 'Motion Sensor | Security Lights | Garden'
    description: "Garden Security Lights automations"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
        id: just_before_sunset
      - platform: state
        entity_id:
          - binary_sensor.garden_sensor_occupancy
        to: "on"
        id: garden_sensor_motion_detected
      - platform: state
        entity_id:
          - binary_sensor.garden_sensor_occupancy
        to: "off"
        for:
          hours: 0
          minutes: 10
          seconds: 0
        id: garden_sensor_area_cleared
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - just_before_sunset
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  brightness_pct: 80
                target:
                  entity_id:
                    - light.garden_security_light_1
                    - light.garden_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - garden_sensor_motion_detected
              - condition: time
                after: "23:00:00"
                weekday:
                  - sun
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
                before: "07:00:00"
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  brightness_pct: 50
                target:
                  entity_id:
                    - light.garden_security_light_1
                    - light.garden_security_light_2
          - conditions:
              - condition: trigger
                id:
                  - garden_sensor_area_cleared
              - condition: time
                after: "23:00:00"
                before: "07:00:00"
                weekday:
                  - sun
                  - mon
                  - tue
                  - wed
                  - thu
                  - fri
                  - sat
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id:
                    - light.garden_security_light_1
                    - light.garden_security_light_2
    
    # use_blueprint:
    #   path: Blackshome/sensor-light.yaml
    #   input:
    #     motion_trigger:
    #       - binary_sensor.garden_sensor_occupancy
    #     light_switch:
    #       area_id: garden
    #     include_light_control:
    #       - use_brightness
    #       - use_colour_temperature
    #       - use_transition
    #     light_brightness: 80
    #     light_colour_temperature: 2700
    #     light_transition_on: 2
    #     light_transition_off: 4
    #     include_sun: sun_disabled
    #     include_ambient: ambient_enabled
    #     ambient_light_sensor: sensor.garden_sensor_illuminance_lux
