automation:

  - id: 'b957b9e4-e1d2-438e-95f7-e73a286e31e4'
    alias: "Routine | Hallway | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - hallway

  - id: '9e20c9f7-4983-4e18-963b-7e61dcd2403b'
    alias: "Routine | Hallway | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - hallway
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

