automation:
  - id: '938f642d-3e9f-44fa-9e2f-ccecc958e094'
    alias: "Turn on the Holiday Lights"
    description: ""
    trigger:
      - platform: time
        at: "06:00:00"
    condition: []
    action:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.holiday_lights
    mode: single

  - id: 'd0f1d9d3-f4d9-4845-ae37-824244d6d9af'
    alias: "Turn on the Outside Holiday Lights before Sunset"
    description: ""
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45:00"
        enabled: true
    condition: []
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          entity_id: light.outside_holiday_lights
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.outside_holiday_switches
      - service: scene.turn_on
        target:
          entity_id: scene.outside_ruby_glow
        metadata: {}
    mode: single
