automation:
  - id: 'ca4989f4-23c1-48d6-8178-fbad657a07b0'
    alias: "It's time to get ready for school"
    description: ""
    trigger:
      - platform: time
        at: "05:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          area_id:
            - dining_room
            - family_room
            - foyer
            - kitchen
      - service: light.turn_on
        data:
          brightness_pct: 40
        target:
          area_id: bathroom
    mode: single

  - id: '3f4c0fdf-d9ef-468e-a973-8e7fa82c7483'
    alias: "Turn on the House at Sunset"
    mode: single
    description: "Lights will turn on 45 minutes before sunset"
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 10
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - back_yard
            - barn
            - camdyn_s_room
            - den
            - dining_room
            - driveway
            - family_room
            - family_room_ambient
            - foyer
            - front_porch
            - front_yard
            - garden
            - hallway
            - kitchen
            - living_room
            - master_bedroom
            - molly_s_room
            - patio
            - side_yard

  - id: 'a85932d9-ff4e-486b-a3a1-89b07e84feef'
    alias: "It's time to Relax"
    description: "The relax scene is activated"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            - family_room_ambient
            - hallway
            - kitchen
            - living_room
            - master_bedroom
            - molly_s_room
            - patio
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  # - id: 'test'
  #   alias: "Test"
  #   description: "Test"
  #   mode: single
  #   trigger:
  #     - platform: time
  #       at: "20:15:00"
  #   condition: []
  #   action:
  #     - service: light.turn_on
  #       target:
  #         entity_id:
  #           - group.security_lights
  #       data:
  #         transition: 5
  #         kelvin: 2237
  #         brightness_pct: 60
  #       metadata: {}

  - id: '92c8fbbb-3b63-4408-95db-82587a3e704b'
    alias: "Turn off the House"
    description: ""
    trigger:
      - platform: device
        type: turned_on
        device_id: 27e9816fa86b7c98dd9c642d9353fbc3
        entity_id: switch.trigger
        domain: switch
    condition:
      - condition: sun
        after: sunset
        enabled: true
    action:
      - service: light.turn_off
        target:
          area_id:
            - basement
            - bathroom
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            - family_room_ambient
            - family_room_holiday
            - foyer
            - front_yard
            - front_yard_holiday
            - hallway
            - living_room
            - kitchen
            - master_bedroom
            - master_closet
            - molly_s_room
            - office
            - patio
            - workshop
        data: {}
      - service: switch.turn_off
        target:
          area_id:
            - master_bathroom
            - bathroom
            - front_yard_holiday
            - hallway
            - workshop
          entity_id:
            - switch.outside_holiday_switches
            - switch.holiday_lights
        data: {}
      - service: light.turn_on
        target:
          entity_id:
            - group.security_lights
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60
        metadata: {}
      - service: fan.turn_on
        data:
          percentage: 33
        target:
          entity_id: fan.master_bedroom_tower_fan
      - service: scene.turn_on
        target:
          entity_id: scene.turn_on_diffuser
        metadata: {}
    mode: single

  # - id: '4770ac3a-35d7-4cf0-8ab8-750f8710341f'
  #   alias: "Turn off the outside yard lights"
  #   description: "Lights turn off at midnight"
  #   trigger:
  #     - platform: time
  #       at: "00:00:00"
  #   condition: []
  #   action:
  #     - service: light.turn_off
  #       data: {}
  #       target:
  #         area_id:
  #           - back_yard
  #           - side_yard
  #           - front_yard
  #   mode: single

  - id: '0743426e-a630-48af-9d91-9728e3ecfff7'
    alias: 'Security Sensor Lights'
    description: ""
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.front_yard_sensor_occupancy
          - binary_sensor.side_yard_sensor_occupancy
        light_switch:
          entity_id: group.security_lights
        end_scenes:
          - scene.security_lights_on
        include_light_control:
          - use_brightness
          - use_colour_temperature
          - use_transition
        light_colour_temperature: 2700
        include_time: time_enabled
        after_time: "23:00:00"
        before_time: "07:00:00"
        light_transition_on: 2
        light_transition_off: 4
