automation:
  - id: 'ca4989f4-23c1-48d6-8178-fbad657a07b0'
    alias: "Routine | House | School Day"
    description: "Turn on the lights to get ready for school"
    mode: single
    trigger:
      - platform: time
        at: "05:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          area_id:
            - dining_room
            - family_room
            - foyer
            - kitchen

  - id: '92c8fbbb-3b63-4408-95db-82587a3e704b'
    alias: "Routine | House | Goodnight"
    description: "Turn off the House"
    mode: single
    trigger:
      - platform: device
        type: turned_on
        device_id: 050e14de5a11adfb770f473c3ed6b540
        entity_id: switch.trigger
        domain: switch
    condition:
      - condition: sun
        after: sunset
        enabled: true
    action:
      - service: light.turn_off
        target:
          area_id:
            - back_yard
            - basement
            - bathroom
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            # - family_room_ambient
            # - family_room_holiday
            - foyer
            - front_yard
            # - front_yard_holiday
            - garden
            - hallway
            - living_room
            - kitchen
            - master_bedroom
            - master_closet
            - molly_s_room
            - office
            - patio
            - side_yard
            - workshop
        data: {}
      - service: switch.turn_off
        target:
          area_id:
            - bathroom
            - camdyn_s_room
            # - family_room_ambient
            # - family_room_holiday
            - front_yard
            # - front_yard_holiday
            - hallway
            - living_room
            - master_bathroom
            - molly_s_room
            - workshop
          entity_id:
            - switch.outside_holiday_switches
            - switch.holiday_lights
        data: {}
      - service: light.turn_on
        target:
          entity_id:
            - light.barn_door_light
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 50
        metadata: {}
      - service: fan.turn_on
        data:
          percentage: 33
        target:
          entity_id: fan.master_bedroom_tower_fan
      - service: scene.turn_on
        target:
          entity_id: scene.turn_on_diffuser
        metadata: {}
