automation:
  - id: 'ca4989f4-23c1-48d6-8178-fbad657a07b0'
    alias: "Routine | House | School Day"
    description: "Turn on the lights to get ready for school"
    mode: single
    trigger:
      - platform: time
        at: "05:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          area_id:
            - dining_room
            - family_room
            - foyer
            - kitchen

  - id: '92c8fbbb-3b63-4408-95db-82587a3e704b'
    alias: "Routine | House | Goodnight"
    description: "Turn off the House"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.good_night
        to: "on"
    condition: []
    action:
      - service: light.turn_off
        target:
          area_id:
            - back_yard
            - basement
            - bathroom
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            - foyer
            - front_porch
            - front_yard
            - front_yard_holiday
            - garden
            - hallway
            - living_room
            - kitchen
            - master_closet
            - molly_s_room
            - office
            - patio
            - side_yard
            - workshop
        data: {}
      - service: switch.turn_off
        target:
          area_id:
            - bathroom
            - camdyn_s_room
            - front_yard
            - hallway
            - living_room
            - master_bathroom
            - molly_s_room
            - workshop
        data: {}
      - service: light.turn_on
        target:
          entity_id:
            - light.barn_door_light
        data:
          transition: 5
          color_temp_kelvin: 2237
          brightness_pct: 50
        metadata: {}
      - delay: 5
      - service: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.good_night

  - id: '050e32fe-5a15-4efb-ba1f-e28db0f99b90'
    alias: "Routine | House | Rainy Day"
    description: "Turn on the lights when the lux goes below 30"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_sensor_occupancy
        to: 'on'
    condition:
      - condition: time
        after: "08:00:00"
        weekday:
          - sun
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
      - condition: sun
        before: sunset
      - condition: numeric_state
        entity_id: sensor.kitchen_sensor_illuminance
        below: "30"
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - den
            - dining_room
            - family_room
            - hallway
            - foyer
            - kitchen
            - living_room
        data:
          transition: 5
          color_temp_kelvin: 2700
          brightness_pct: 60
