automation:
  - id: 'ca4989f4-23c1-48d6-8178-fbad657a07b0'
    alias: "Routine | House | School Day"
    description: "Turn on the lights to get ready for school"
    mode: single
    trigger:
      - platform: time
        at: "05:45:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
        target:
          area_id:
            - dining_room
            - family_room
            - foyer
            - kitchen
      - service: light.turn_on
        data:
          brightness_pct: 30
        target:
          area_id: bathroom

  - id: '3f4c0fdf-d9ef-468e-a973-8e7fa82c7483'
    alias: "Routine | Sunset | Inside"
    description: "Turn on the lights 45 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:45"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 10
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - camdyn_s_room
            - den
            - dining_room
            - driveway
            - family_room
            - family_room_ambient
            - foyer
            - front_porch
            - hallway
            - kitchen
            - living_room
            - master_bedroom
            - molly_s_room
            - patio

  - id: 'a85932d9-ff4e-486b-a3a1-89b07e84feef'
    alias: "Routine | House | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            - family_room_ambient
            - foyer
            - hallway
            - kitchen
            - living_room
            - master_bedroom
            - molly_s_room
            - patio
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: '92c8fbbb-3b63-4408-95db-82587a3e704b'
    alias: "Routine | House | Goodnight"
    description: "Turn off the House"
    mode: single
    trigger:
      - platform: device
        type: turned_on
        device_id: 27e9816fa86b7c98dd9c642d9353fbc3
        entity_id: switch.trigger
        domain: switch
    condition:
      - condition: sun
        after: sunset
        enabled: true
    action:
      - service: light.turn_off
        target:
          area_id:
            - back_yard
            - basement
            - bathroom
            - camdyn_s_room
            - den
            - dining_room
            - family_room
            - family_room_ambient
            - family_room_holiday
            - foyer
            - front_yard
            - front_yard_holiday
            - garden
            - hallway
            - living_room
            - kitchen
            - master_bedroom
            - master_closet
            - molly_s_room
            - office
            - patio
            - side_yard
            - workshop
        data: {}
      - service: switch.turn_off
        target:
          area_id:
            - bathroom
            - camdyn_s_room
            - family_room_ambient
            - family_room_holiday
            - front_yard
            - front_yard_holiday
            - hallway
            - living_room
            - master_bathroom
            - molly_s_room
            - office
            - workshop
          entity_id:
            - switch.outside_holiday_switches
            - switch.holiday_lights
        data: {}
      - service: light.turn_on
        target:
          entity_id:
            - light.barn_door_light
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 50
        metadata: {}
      - service: fan.turn_on
        data:
          percentage: 33
        target:
          entity_id: fan.master_bedroom_tower_fan
      - service: scene.turn_on
        target:
          entity_id: scene.turn_on_diffuser
        metadata: {}
