automation:

  - id: 'e75e2a71-c66d-4db8-bcc2-dd856e373c1f'
    alias: "Routine | Kitchen | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - dining_room
            - kitchen

  - id: 'f53f40a7-08e6-469c-8fe9-779e21ede6c3'
    alias: "Routine | Kitchen | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - dining_room
            - kitchen
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: '03ced7e8-00d7-445a-8efb-5c16815c0bbb'
    alias: "Routine | House | Dinner Time"
    description: "Turn the lights on in the kitchen to start making dinner"
    trigger:
      - platform: time
        at: "16:45:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
          transition: 900
        target:
          area_id:
            - kitchen
            - dining_room
    mode: single
