automation:
  - alias: "It's time to make dinner"
    id: 03ced7e8-00d7-445a-8efb-5c16815c0bbb
    description: "Turn the lights on in the kitchen to start making dinner"
    trigger:
      - platform: time
        at: "16:45:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          brightness_pct: 100
          transition: 900
        target:
          area_id:
            - kitchen
            - dining_room
    mode: single
