automation:

  - id: '73db59ea-b4ef-4b9e-9990-ee8bf6be994c'
    alias: "Routine | Living Room | Sunrise"
    description: "Turn off the lights 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: time
        at: "08:00:00"
    condition: []
    action:
      - service: light.turn_off
        data:
          transition: 2
        target:
          area_id: &areas
            - living_room

  - id: '0e7b26f8-d2f6-439b-bde6-ca100d8570e7'
    alias: "Routine | Living Room | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id: *areas

  - id: '499a815a-3962-4d7b-9f91-90e0906ec376'
    alias: "Routine | Living Room | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60
        target:
          area_id: *areas

  - id: '98060966-fabb-4b4b-ae63-4b45f1b6b13c'
    alias: "Routine | Living Room | Away"
    description: "Everyone has left the house, turn off the Living Room Lights if the time is before sunset"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.family_home
        from: "on"
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: sun
        before: sunset
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 2
        target:
          area_id: *areas
