automation:
- id: 'a54f6e03-4ce2-4fe0-8cb3-923cba043e23'
  alias: Notification | Mail Box | Mailbox Opened
  description: "Send a notification when the mailbox is opened"
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.mailbox_guard_motion
      to: "on"
  condition: []
  action:
    - service: notify.parent_devices
      data:
        title: Mailbox Opened!
        message: The mailbox was opened.
        data:
          url: /lovelace/home
          persistent: true
          importance: high
          channel: MailBox
          tag: mailbox
          image: /media/local/notify/mailbox.jpg
          actions:
            - action: received
              title: I checked the mailbox
    - service: input_number.set_value
      data:
        entity_id: input_number.mailbox_guard_count
        value: "{{ (states.input_number.mailbox_guard_count.state | int) + 1 }}"
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.mailbox_guard_motion

- id: '95dc4665-c395-4a9a-b877-df95b7d54664'
  alias: Notification | Mail Box | Low Battery
  description: "Send a notification the mailbox sensor battery is low"
  mode: single
  trigger:
    - platform: state
      entity_id: input_boolean.mailbox_guard_low_battery
      to: "on"
  condition: []
  action:
    - service: notify.parent_devices
      data:
        message: Mailbox Guard Low Battery!
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.mailbox_guard_low_battery
