automation:
  
  - id: '0fbc2f32-4ac7-432d-a3dc-98dc15f48e5c'
    alias: "Routine | Sunset | Master Bedroom"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - master_bedroom

  - id: 'c03a9f48-2c98-4d19-a10c-64b3bef2a9bd'
    alias: "Routine | Relax | Master Bedroom"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - master_bedroom
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: 'b1d2683a-f4a9-4b73-a915-1550141d2522'
    alias: 'Routine | Wake Up | Master Bedroom'
    description: "Master Bedroom devices turn off when it's morning and Dan and Stephanie are out of bed for at least 2 minutes"
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ expand('binary_sensor.sleepnumber_our_bed_daniel_is_in_bed', 'binary_sensor.sleepnumber_our_bed_stephanie_is_in_bed') | selectattr('state', 'eq', 'off') | list | count == 2 }}
      # - platform: state
      #   entity_id:
      #     - binary_sensor.sleepnumber_our_bed_daniel_is_in_bed
      #   to: "off"
      #   for:
      #     hours: 0
      #     minutes: 2
      #     seconds: 0
      #   id: out-of-bed-dan
      # - platform: state
      #   entity_id:
      #     - binary_sensor.sleepnumber_our_bed_stephanie_is_in_bed
      #   to: "off"
      #   for:
      #     hours: 0
      #     minutes: 2
      #     seconds: 0
      #   id: out-of-bed-steph
    condition:
      - condition: sun
        after: sunrise
    action:
      - service: fan.turn_off
        target:
          entity_id: fan.master_bedroom_tower_fan
        data: {}
      - service: humidifier.turn_off
        target:
          entity_id: humidifier.master_bedroom_diffuser
        data: {}

  - id: '5deb15f3-7639-42fb-a069-7235643c3408'
    alias: "Switch | Lights | Master Bedroom"
    description: "Master Bedroom Switch turns Master Bedroom Lights on or off, dimming capable"
    mode: queued
    max: 10
    trigger:
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: config_single
        id: master_bedroom_light_switch_config_single
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: config_double
        id: master_bedroom_light_switch_config_double
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: config_triple
        id: master_bedroom_light_switch_config_triple
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: up_single
        id: master_bedroom_light_switch_up_single
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: down_single
        id: master_bedroom_light_switch_down_single
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: up_double
        id: master_bedroom_light_switch_up_double
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: down_double
        id: master_bedroom_light_switch_down_double
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: up_held
        id: master_bedroom_light_switch_up_held
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: down_held
        id: master_bedroom_light_switch_down_held
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: up_release
        id: master_bedroom_light_switch_up_release
      - platform: device
        domain: mqtt
        device_id: 1f9d22b45512f619dcb3cb26d1922941
        type: action
        subtype: down_release
        id: master_bedroom_light_switch_down_release
      - platform: state
        entity_id:
          - light.master_bedroom_light_1
        to: "on"
        id: master_bedroom_light_1_turns_on
      - platform: state
        entity_id:
          - light.master_bedroom_light_1
        to: "off"
        id: master_bedroom_light_1_turns_off
      - platform: state
        entity_id:
          - light.master_bedroom_light_switch
        id: master_bedroom_light_switch_local_dimming
        enabled: true
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_switch_up_single
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id: 
                    - light.master_bedroom_light_1
                    - light.master_bedroom_light_2
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_switch_down_single
            sequence:
              - service: light.turn_off
                target:
                  entity_id: 
                    - light.master_bedroom_light_1
                    - light.master_bedroom_light_2
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_switch_up_double
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id: 
                    - light.master_bedroom_light_1
                    - light.master_bedroom_light_2
                alias: Light 'Turn on' on Master Bedroom to Bright
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_switch_down_double
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  kelvin: 2700
                  brightness_pct: 30
                target:
                  entity_id: 
                    - light.master_bedroom_light_1
                    - light.master_bedroom_light_2
                alias: Light 'Turn on' on Master Bedroom to Nightlight
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_1_turns_on
            sequence:
              - service: light.turn_on
                target:
                  device_id: 1f9d22b45512f619dcb3cb26d1922941
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_1_turns_off
            sequence:
              - service: light.turn_off
                target:
                  device_id: 1f9d22b45512f619dcb3cb26d1922941
                data: {}
          - conditions:
              - condition: trigger
                id:
                  - master_bedroom_light_switch_local_dimming
              - condition: template
                value_template: >-
                  {{ states.light.master_bedroom_light_switch.last_updated > states.light.master_bedroom_light_1.last_changed }}
            sequence:
              - service: light.turn_on
                entity_id: 
                  - light.master_bedroom_light_1
                  - light.master_bedroom_light_2
                data:
                  transition: 2
                  kelvin: 2700
                  brightness: "{{ state_attr('light.master_bedroom_light_switch', 'brightness') | default(0, true) }}"
