automation:
  - id: '23edfdb2-f2f6-4df2-9879-7c83856d1820'
    alias: "Master Bathroom Motion Sensor Turns On Ambient Lights"
    description: >-
      Master Bathroom Motion Sensor turns on ambient lights, schedules them to turn
      off, and dims them at night
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.master_bathroom_motion_sensor_motion
        light_switch:
          entity_id: light.master_bathroom_lightstrip
        time_delay: 10
        include_light_control:
          - use_brightness
          - use_transition
        light_transition_on: 2
        light_transition_off: 2
        include_night_lights: night_lights_enabled
        night_lights:
          entity_id: light.master_bathroom_lightstrip
        night_time_delay: 3
        include_night_light_control:
          - use_brightness
          - use_transition
        night_lights_conditions:
          - time_enabled
        night_lights_after_time: "23:00:00"
        night_lights_before_time: "08:00:00"