automation:
  - id: '8e954b7f-6483-495e-918a-651e12b1a501'
    alias: "Master Closet Motion Sensor Triggered"
    description: "Turn on Master Closet Downlight when Master Closet Motion Sensor is triggered"
    use_blueprint:
      path: homeassistant/Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.master_closet_sensor_motion
        light_switch:
          entity_id: light.master_closet
        time_delay: 10
        include_light_control:
          - use_brightness
          - use_transition
        light_transition_on: 2
        light_transition_off: 2
        include_night_lights: night_lights_enabled
        night_lights:
          entity_id: light.master_closet
        night_time_delay: 3
        include_night_light_control:
          - use_brightness
          - use_transition
        night_light_brightness: 20
        night_lights_conditions:
          - time_enabled
        night_lights_after_time: "23:00:00"
        night_lights_before_time: "08:00:00"
  
  - id: '9997e2eb-b0d2-4c49-8a68-67727e6a0f48'
    alias: "Master Closet Lutron Aurora Toggles Light On/Off"
    description: "Toggle Master Closet Downlight when Master Closet Lutron Aurora is tapped"
    trigger:
      - platform: state
        entity_id: event.master_closet_aurora_button_1
    action:
      - service: light.toggle
        data: {}
        target:
          area_id: master_closet
    mode: single
