automation:
  - id: c111b69b-daed-49da-abe1-bafd8dfbaba3
    alias: Master Bathroom Motion Sensor Turns On Ambient Lights
    description: Master Bathroom Motion Sensor turns on ambient lights, schedules them to turn off, and dims them at night
    use_blueprint:
      path: homeassistant/Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.master_bathroom_motion_sensor_motion
        light_switch:
          entity_id: light.master_bathroom_ambient
        time_delay: 10
        include_light_control:
          - use_brightness
          - use_transition
        light_transition_on: 2
        light_transition_off: 2
        include_night_lights: night_lights_enabled
        night_lights:
          entity_id: light.master_bathroom_ambient
        night_time_delay: 3
        include_night_light_control:
          - use_brightness
        night_light_brightness: 20
        night_lights_conditions:
          - time_enabled
        night_lights_after_time: "23:00:00"
        night_lights_before_time: "08:00:00"
