automation:
  
  - id: '0fbc2f32-4ac7-432d-a3dc-98dc15f48e5c'
    alias: "Routine | Sunset | Master Bedroom"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - master_bedroom

  - id: 'c03a9f48-2c98-4d19-a10c-64b3bef2a9bd'
    alias: "Routine | Relax | Master Bedroom"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - master_bedroom
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: 'b1d2683a-f4a9-4b73-a915-1550141d2522'
    alias: 'Routine | Wake Up | Master Bedroom'
    description: "Master Bedroom devices turn off when it's morning and Dan and Stephanie are out of bed for at least 2 minutes"
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {{ expand('binary_sensor.sleepnumber_our_bed_daniel_is_in_bed', 'binary_sensor.sleepnumber_our_bed_stephanie_is_in_bed') | selectattr('state', 'eq', 'off') | list | count == 2 }}
      # - platform: state
      #   entity_id:
      #     - binary_sensor.sleepnumber_our_bed_daniel_is_in_bed
      #   to: "off"
      #   for:
      #     hours: 0
      #     minutes: 2
      #     seconds: 0
      #   id: out-of-bed-dan
      # - platform: state
      #   entity_id:
      #     - binary_sensor.sleepnumber_our_bed_stephanie_is_in_bed
      #   to: "off"
      #   for:
      #     hours: 0
      #     minutes: 2
      #     seconds: 0
      #   id: out-of-bed-steph
    condition:
      - condition: sun
        after: sunrise
    action:
      - service: fan.turn_off
        target:
          entity_id: fan.master_bedroom_tower_fan
        data: {}
      - service: humidifier.turn_off
        target:
          entity_id: humidifier.master_bedroom_diffuser
        data: {}
