automation:
  
  - id: '0fbc2f32-4ac7-432d-a3dc-98dc15f48e5c'
    alias: "Routine | Master Bedroom | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          entity_id: &entities
            - light.master_bedroom_light_1
            - light.master_bedroom_light_2
            - light.master_bedroom_light_switch

  - id: 'c03a9f48-2c98-4d19-a10c-64b3bef2a9bd'
    alias: "Routine | Master Bedroom | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          entity_id: *entities
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: '84be444f-0bc8-44a1-ba92-afa951459267'
    alias: "Routine | Master Bedroom | Away"
    description: "Everyone has left the house, turn off the Master Bedroom Lights if the time is before sunset"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.parents_home
        from: "on"
        to: "off"
        for:
          minutes: 5
    condition:
      - condition: sun
        before: sunset
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 2
        target:
          entity_id: *entities

  - id: 'b1d2683a-f4a9-4b73-a915-1550141d2522'
    alias: 'Routine | Master Bedroom | Wake Up'
    description: "Master Bedroom devices turn off when it's morning and Dan and Stephanie are out of bed for at least 3 minutes"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.we_are_out_of_bed
        to: "on"
        for:
          hours: 0
          minutes: 3
          seconds: 0
    condition: 
      - condition: time
        before: "10:00:00"
    action:
      - service: humidifier.turn_off
        target:
          entity_id: humidifier.master_bedroom_diffuser
        data: {}
      - service: fan.turn_off
        target:
          entity_id: fan.master_bedroom_tower_fan
        data: {} 

  - id: 'f4f7be88-33bd-4c61-b246-c74347d14a5e'
    alias: "Routine | Master Bedroom | Goodnight"
    description: "Turn off the Master Bedroom"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.good_night
        to: "on"
    condition: []
    action:
      - service: light.turn_off
        target:
          area_id:
            - master_bedroom
      - service: fan.turn_on
        data:
          percentage: 33
        target:
          entity_id: fan.master_bedroom_tower_fan
        metadata: {}

  - id: '152dd72a-4354-41bf-ab8a-ec2c260dba0f'
    alias: "Routine | Master Bedroom | Goodnight when Dan is Home"
    description: "Turn off the Master Bedroom, but only when Dan is at home"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_boolean.good_night
        to: "on"
    condition:
      # - condition: sun
      #   after: sunset
      #   enabled: true
      - condition: state
        entity_id: person.daniel_frey
        state: home
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.turn_on_diffuser
        metadata: {}
