automation:
  - id: '8e954b7f-6483-495e-918a-651e12b1a501'
    alias: "Master Closet Motion Sensor Actions"
    description: "Turn on Master Closet Downlight when Master Closet Motion Sensor is triggered"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_closet_sensor_occupancy
        to: "on"
        id: master_closet_sensor_motion_detected
      - platform: state
        entity_id:
          - binary_sensor.master_closet_sensor_occupancy
        to: "off"
        id: master_closet_sensor_area_cleared
        for:
          hours: 0
          minutes: 10
          seconds: 0
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - master_closet_sensor_motion_detected
            sequence:
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 2
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  entity_id: light.master_closet_downlight
          - conditions:
              - condition: trigger
                id:
                  - master_closet_sensor_area_cleared
            sequence:
              - service: light.turn_off
                metadata: {}
                data:
                  transition: 4
                target:
                  entity_id: light.master_closet_downlight
          
  # - id: '9997e2eb-b0d2-4c49-8a68-67727e6a0f48'
  #   alias: "Master Closet Inovelli Smart 2-1 Switch Turns Light On"
  #   description: "Turns Master Closet Downlight on when Master Closet Switch up button is pressed"
  #   trigger:
  #     - platform: device
  #       type: turned_off
  #       device_id: 4d36702c12c013b50f5519e7583c4024
  #       entity_id: 2af3f039ab8dd7383c92eb0315d3f1b0
  #       domain: light
  #   action:
  #     - service: light.turn_on
  #       data: {}
  #       target:
  #         area_id: master_closet
  #   mode: single

  # - id: '14cf4b1c-d8cd-44e4-8bf9-ac94203c6a16'
  #   alias: "Master Closet Inovelli Smart 2-1 Switch Turns Light Off"
  #   description: "Turns Master Closet Downlight off when Master Closet Switch down button is pressed"
  #   trigger:
  #     - platform: device
  #       type: turned_off
  #       device_id: 4d36702c12c013b50f5519e7583c4024
  #       entity_id: 2af3f039ab8dd7383c92eb0315d3f1b0
  #       domain: light
  #   action:
  #     - service: light.turn_off
  #       data: {}
  #       target:
  #         area_id: master_closet
  #   mode: single
