automation:
  - id: '8e954b7f-6483-495e-918a-651e12b1a501'
    alias: "Master Closet Motion Sensor Triggered"
    description: "Turn on Master Closet Downlight when Master Closet Motion Sensor is triggered"
    use_blueprint:
      path: homeassistant/Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.master_closet_sensor_occupancy
        light_switch:
          area_id: master_closet
        time_delay: 10
        include_light_control:
          - use_brightness
          - use_transition
        light_transition_on: 2
        light_transition_off: 2
        include_night_lights: night_lights_enabled
        night_lights:
          area_id: master_closet
        night_time_delay: 3
        include_night_light_control:
          - use_brightness
          - use_transition
        night_light_brightness: 20
        night_lights_conditions:
          - time_enabled
        night_lights_after_time: "23:00:00"
        night_lights_before_time: "08:00:00"
  
  # - id: '9997e2eb-b0d2-4c49-8a68-67727e6a0f48'
  #   alias: "Master Closet Inovelli Smart 2-1 Switch Turns Light On"
  #   description: "Turns Master Closet Downlight on when Master Closet Switch up button is pressed"
  #   trigger:
  #     - platform: device
  #       type: turned_off
  #       device_id: 4d36702c12c013b50f5519e7583c4024
  #       entity_id: 2af3f039ab8dd7383c92eb0315d3f1b0
  #       domain: light
  #   action:
  #     - service: light.turn_on
  #       data: {}
  #       target:
  #         area_id: master_closet
  #   mode: single

  # - id: '14cf4b1c-d8cd-44e4-8bf9-ac94203c6a16'
  #   alias: "Master Closet Inovelli Smart 2-1 Switch Turns Light Off"
  #   description: "Turns Master Closet Downlight off when Master Closet Switch down button is pressed"
  #   trigger:
  #     - platform: device
  #       type: turned_off
  #       device_id: 4d36702c12c013b50f5519e7583c4024
  #       entity_id: 2af3f039ab8dd7383c92eb0315d3f1b0
  #       domain: light
  #   action:
  #     - service: light.turn_off
  #       data: {}
  #       target:
  #         area_id: master_closet
  #   mode: single
