automation:

  - id: '23edfdb2-f2f6-4df2-9879-7c83856d1820'
    alias: "Motion Sensor | Master Bathroom | Ambient"
    description: >-
      Master Bathroom Motion Sensor turns on ambient lights, schedules them to turn
      off, and dims them at night
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_bathroom_sensor_occupancy
        to: "on"
        id: master_bathroom_sensor_detected
      - platform: state
        entity_id:
          - binary_sensor.master_bathroom_sensor_occupancy
        to: "off"
        for:
          hours: 0
          minutes: 3
          seconds: 0
        id: master_bathroom_sensor_area_cleared
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - master_bathroom_sensor_area_cleared
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.master_bathroom_lightstrip
                data:
                  transition: 2
          - conditions:
              - condition: trigger
                id:
                  - master_bathroom_sensor_detected
              - condition: state
                entity_id: schedule.daytime
                state: "on"
            sequence:
              - service: light.turn_on
                target:
                  area_id: master_bathroom
                data:
                  transition: 2
                  kelvin: 2700
                  brightness_pct: 100
          - conditions:
              - condition: trigger
                id:
                  - master_bathroom_sensor_detected
              - condition: state
                entity_id: schedule.daytime
                state: "off"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.master_bathroom_lightstrip
                data:
                  transition: 2
                  brightness_pct: 20
                  kelvin: 2237

  - id: 'f0a25d51-92a9-4918-a033-87211ca59ee1'
    alias: "Routine | Master Bathroom | Away"
    description: "Turn off the master bathroom lights when the parents are away"
    mode: single
    initial_state: true
    trigger:
      platform: state
      entity_id: binary_sensor.parents_home
      from: "on"
      to: "off"
      for:
        minutes: 5
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target: &areas
          - master_bathroom
      - service: switch.turn_off
        metadata: {}
        data: {}
        target: *areas
