automation:
  
  - id: '68890773-dafe-4248-824f-83efc7591979'
    alias: "Routine | Sunset | Molly's Room"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - molly_s_room

  - id: 'c1f67ab1-d41b-4073-9a69-4345b4604260'
    alias: "Routine | Relax | Molly's Room"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - molly_s_room
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

  - id: '69139fbb-ad53-4b80-9944-56f12d8aa90f'
    alias: "Routine | Molly's Room | Molly is at school"
    description: "She arrived at school, turn off the lights"
    mode: single
    trigger:
      - platform: zone
        entity_id: person.molly_frey
        zone: zone.southern_lehigh_high_school
        event: enter
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: molly_s_room

  - id: '48aa24e0-cc57-4923-9061-efa2cbdfedda'
    alias: "Switch | Lights | Molly's Room"
    description: "Molly's Room Dimmer Switch turns Molly's Room Lights on or off, dimming capable"
    mode: queued
    max: 10
    trigger:
      - platform: device
        domain: mqtt
        device_id: c7343bb67fd77e58872ebabf8a65a784
        type: action
        subtype: on_press
        id: molly_s_room_button_on_press
      - platform: device
        domain: mqtt
        device_id: c7343bb67fd77e58872ebabf8a65a784
        type: action
        subtype: up_press
        id: molly_s_room_button_up_press
      - platform: device
        domain: mqtt
        device_id: c7343bb67fd77e58872ebabf8a65a784
        type: action
        subtype: down_press_release
        id: molly_s_room_button_down_press
      - platform: device
        domain: mqtt
        device_id: c7343bb67fd77e58872ebabf8a65a784
        type: action
        subtype: off_press
        id: molly_s_room_button_off_press
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - molly_s_room_button_on_press
            sequence:
              - service: light.turn_on
                target:
                  area_id: molly_s_room
                data:
                  transition: 1
                  kelvin: 2700
                  brightness_pct: 100
          - conditions:
              - condition: trigger
                id:
                  - molly_s_room_button_off_press
            sequence:
              - service: light.turn_off
                target:
                  area_id: molly_s_room
                data:
                  transition: 1
          - conditions:
              - condition: trigger
                id:
                  - molly_s_room_button_up_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: 
                    - light.molly_s_room_light_1
                    - light.molly_s_desk_light
                data:
                  brightness_step_pct: 10
                  kelvin: 2700
          - conditions:
              - condition: trigger
                id:
                  - molly_s_room_button_down_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: 
                    - light.molly_s_room_light_1
                    - light.molly_s_desk_light
                data:
                  brightness_step_pct: -10
                  kelvin: 2700
