automation:
  - id: 'ea14801e-829f-4b4c-8f2f-fd653116528e'
    alias: "Open for Business"
    description: ""
    trigger:
      - platform: time
        at: "08:10:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 10
          color_temp: 400
          brightness_pct: 100
        target:
          area_id: office
    mode: single

  - id: '49cb1865-323a-4211-8298-cafcd33ccd9b'
    alias: "Close the Office"
    description: ""
    trigger:
      - platform: time
        at: "18:00:00"
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: office
    mode: single

  - id: '9a0d7561-ae4c-409c-aa82-aa615f1efe08'
    alias: "Office Switch - On"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: on_press
        discovery_id: 0x0017880104e5ab52 action_on_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 10
          color_temp: 400
          brightness_pct: 100
        target:
          area_id: office
    mode: single

  - id: 'ce4b4261-eec9-4224-b8be-5bb24281af49'
    alias: "Office Switch - Off"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: off_press
        discovery_id: 0x0017880104e5ab52 action_off_press
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 5
        target:
          area_id: office
    mode: single

  - id: '4989a5d9-3fb3-4b62-a5d0-63077c957d25'
    alias: "Office Switch - Dimmer - Increase Brightness"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: up_press
        discovery_id: 0x0017880104e5ab52 action_up_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          area_id: office
    mode: single

  - id: '1c98a193-d77b-42c7-bb55-606ead3c2e33'
    alias: "Office Switch - Dimmer - Decrease Brightness"
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: down_press
        discovery_id: 0x0017880104e5ab52 action_down_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          area_id: office
    mode: single
