automation:
  - alias: "Close the Office"
    id: 49cb1865-323a-4211-8298-cafcd33ccd9b
    description: ""
    trigger:
      - platform: time
        at: "18:00:00"
    condition: []
    action:
      - service: light.turn_off
        data: {}
        target:
          area_id: office
    mode: single

  - alias: "Office Switch - On"
    id: 9a0d7561-ae4c-409c-aa82-aa615f1efe08
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: on_press
        discovery_id: 0x0017880104e5ab52 action_on_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 10
          color_temp: 400
          brightness_pct: 100
        target:
          area_id: office
    mode: single

  - alias: "Office Switch - Off"
    id: ce4b4261-eec9-4224-b8be-5bb24281af49
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: off_press
        discovery_id: 0x0017880104e5ab52 action_off_press
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data:
          transition: 5
        target:
          area_id: office
    mode: single

  - alias: "Office Switch - Dimmer - Increase Brightness"
    id: 4989a5d9-3fb3-4b62-a5d0-63077c957d25
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: up_press
        discovery_id: 0x0017880104e5ab52 action_up_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 10
        target:
          area_id: office
    mode: single

  - alias: "Office Switch - Dimmer - Decrease Brightness"
    id: 1c98a193-d77b-42c7-bb55-606ead3c2e33
    description: ""
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: down_press
        discovery_id: 0x0017880104e5ab52 action_down_press
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -10
        target:
          area_id: office
    mode: single

  - alias: Dan's Office Cube
    id: 8e854a44-6042-481b-bf0c-279e33e26e74
    description: ""
    trigger:
      # slide
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: slide
        id: slide

      # tap
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: tap
        id: tap
      
      # rotate right
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: rotate_right
        id: rotate_right

      # rotate left
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: rotate_left
        id: rotate_left

      # shake
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: shake
        id: shake
      
      # throw
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: throw
        id: throw
      
      # flip 90 degrees
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_from_side
        to: flip90
        id: flip90
      
      # angle
      - platform: state
        entity_id: sensor.dan_s_office_cube_action_angle
        id: angle
      
    action:
      - choose:

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '1'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '2'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '3'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '4'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '5'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}

        - conditions:
          - condition: state
            entity_id: sensor.dan_s_office_cube_side
            state: '6'
          - condition: trigger
            id: flip90
          sequence:
          - service: light.toggle
            target:
              area_id: office
            data: {}
