automation:
  - id: 'ea14801e-829f-4b4c-8f2f-fd653116528e'
    alias: "Open for Business"
    description: ""
    trigger:
      - platform: time
        at: "08:10:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        data:
          transition: 10
          color_temp: 400
          brightness_pct: 100
        target:
          area_id: office
    mode: single

  - id: '49cb1865-323a-4211-8298-cafcd33ccd9b'
    alias: "Close the Office"
    description: ""
    trigger:
      - platform: time
        at: "18:00:00"
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: office
    mode: single

  - id: 'c9759972-32b1-4b2d-bc11-d695273c1aff'
    alias: "Switch | Automation | Office"
    description: "Office Switch turns Office Lights on or off, dimming capable"
    mode: queued
    max: 10
    trigger:
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: on_press
        id: office_button_on_press
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: up_press
        id: office_button_up_press
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: down_press_release
        id: office_button_down_press
      - platform: device
        domain: mqtt
        device_id: 5d9b84a9ff8a24af51ff01e75e3a293b
        type: action
        subtype: off_press
        id: office_button_off_press
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - office_button_on_press
            sequence:
              - service: light.turn_on
                target:
                  area_id: office
                data:
                  transition: 1
                  kelvin: 2700
                  brightness_pct: 100
          - conditions:
              - condition: trigger
                id:
                  - office_button_off_press
            sequence:
              - service: light.turn_off
                target:
                  area_id: office
                data:
                  transition: 1
          - conditions:
              - condition: trigger
                id:
                  - office_button_up_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_light_1
                data:
                  brightness_step_pct: 10
                  kelvin: 2700
          - conditions:
              - condition: trigger
                id:
                  - office_button_down_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_light_1
                data:
                  brightness_step_pct: -10
                  kelvin: 2700
