automation:
  - id: 'ea14801e-829f-4b4c-8f2f-fd653116528e'
    alias: "Routine | Office | Workday"
    description: "It's time to go to work"
    mode: single
    trigger:
      - platform: time
        at: "08:10:00"
        id: workday_start
      - platform: time
        at: "10:00:00"
        id: workday_mid_morning
      - platform: time
        at: "13:00:00"
        id: workday_lunch
      - platform: time
        at: "14:00:00"
        id: workday_after_lunch
      - platform: time
        at: "15:30:00"
        id: workday_mid_afternoon
      - platform: time
        at: "16:45:00"
        id: workday_evening
    condition:
      - condition: zone
        entity_id: person.daniel_frey
        zone: zone.home
      - condition: state
        entity_id: binary_sensor.work_day
        state: "on"
      - condition: not
        conditions:
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.work_holiday
                state: "on"
              - condition: state
                entity_id: binary_sensor.work_travel
                state: "on"
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - workday_start
            sequence: 
              - service: light.turn_on
                metadata: {}
                data:
                  transition: 1
                  kelvin: 2700
                  brightness_pct: 100
                target:
                  area_id: office
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: It's time to start your work day. Have a great day!
                target:
                  entity_id: tts.google_en_com
          - conditions:
              - condition: trigger
                id:
                  - workday_mid_morning
            sequence: 
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: It's time to stand up and stretch. Let's take a break for 10 minutes.
                target:
                  entity_id: tts.google_en_com
          - conditions:
              - condition: trigger
                id:
                  - workday_lunch
            sequence: 
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: It's time for lunch! Remember to wash your hands!
                target:
                  entity_id: tts.google_en_com
          - conditions:
              - condition: trigger
                id:
                  - workday_after_lunch
            sequence: 
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: Hope your having a good day! Wamt to go for a walk?
                target:
                  entity_id: tts.google_en_com
          - conditions:
              - condition: trigger
                id:
                  - workday_mid_afternoon
            sequence: 
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: Let's go grab a glass of water. And why don't you go wash your hands?
                target:
                  entity_id: tts.google_en_com
          - conditions:
              - condition: trigger
                id:
                  - workday_evening
            sequence: 
              - service: tts.speak
                metadata: {}
                data:
                  cache: true
                  media_player_entity_id: media_player.office
                  message: Time to start wrapping up your work day and plan for dinner!
                target:
                  entity_id: tts.google_en_com


  - id: '49cb1865-323a-4211-8298-cafcd33ccd9b'
    alias: "Routine | Office | Close the Office"
    description: "The Office is closed"
    mode: single
    trigger:
      - platform: time
        at: "18:00:00"
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: office

  - id: 'c9759972-32b1-4b2d-bc11-d695273c1aff'
    alias: "Switch | Lights | Office"
    description: "Office Switch turns Office Lights on or off, dimming capable"
    mode: queued
    max: 10
    trigger:
      - platform: device
        domain: mqtt
        device_id: 1cedae21877c5db501217cf2b5de0c28
        type: action
        subtype: on_press
        id: office_button_on_press
      - platform: device
        domain: mqtt
        device_id: 1cedae21877c5db501217cf2b5de0c28
        type: action
        subtype: up_press
        id: office_button_up_press
      - platform: device
        domain: mqtt
        device_id: 1cedae21877c5db501217cf2b5de0c28
        type: action
        subtype: down_press_release
        id: office_button_down_press
      - platform: device
        domain: mqtt
        device_id: 1cedae21877c5db501217cf2b5de0c28
        type: action
        subtype: off_press
        id: office_button_off_press
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - office_button_on_press
            sequence:
              - service: light.turn_on
                target:
                  area_id: office
                data:
                  transition: 1
                  kelvin: 2700
                  brightness_pct: 100
          - conditions:
              - condition: trigger
                id:
                  - office_button_off_press
            sequence:
              - service: light.turn_off
                target:
                  area_id: office
                data:
                  transition: 1
          - conditions:
              - condition: trigger
                id:
                  - office_button_up_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_light_1
                data:
                  brightness_step_pct: 10
                  kelvin: 2700
          - conditions:
              - condition: trigger
                id:
                  - office_button_down_press
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.office_light_1
                data:
                  brightness_step_pct: -10
                  kelvin: 2700
