automation:

  - id: '4770ac3a-35d7-4cf0-8ab8-750f8710341f'
    alias: "Routine | House | Security Lights Turn off"
    description: "Security Lights turn off 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:45:00"
    condition: []
    action:
      - service: light.turn_off
        data: {}
        target:
          entity_id: 
            - light.front_door_light
            - light.back_door_light
            - light.driveway_security_light
            - light.barn_door_light
