automation:

  - id: '4770ac3a-35d7-4cf0-8ab8-750f8710341f'
    alias: "Turn off the Security Lights"
    description: "Lights turn off 45 minutes after sunrise"
    mode: single
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:45:00"
    condition: []
    action:
      - service: light.turn_off
        data: {}
        target:
          entity_id: group.security_lights

  - id: '94a804a6-9105-42db-84bc-745b571aeba3'
    alias: 'Side Yard Security Sensor Lights'
    description: ""
    use_blueprint:
      path: Blackshome/sensor-light.yaml
      input:
        motion_trigger:
          - binary_sensor.back_yard_sensor_occupancy
          - binary_sensor.side_yard_sensor_occupancy
        light_switch:
          entity_id:
            - light.back_yard_security_light_1
            - light.back_yard_security_light_2
            - light.side_yard_security_light_1
            - light.side_yard_security_light_2
            - light.side_yard_security_light_3
            - light.side_yard_security_light_4
        include_light_control:
          - use_brightness
          - use_colour_temperature
          - use_transition
        light_colour_temperature: 2700
        light_brightness: 80
        include_time: time_enabled
        after_time: "23:00:00"
        before_time: "07:00:00"
        light_transition_on: 2
        light_transition_off: 4
