automation:

  - id: 'd1e5d21c-a46d-48ed-b2e0-9a35d1d2ad24'
    alias: "Routine | Patio | Sunset"
    description: "Turn on the lights 30 minutes before sunset"
    mode: single
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    condition: []
    action:
      - service: light.turn_on
        data:
          transition: 2
          kelvin: 2700
          brightness_pct: 100
        target:
          area_id:
            - patio

  - id: '1ab71119-81b3-4b1c-ae7d-803c79446bd1'
    alias: "Routine | Patio | Relax"
    description: "It's time to relax"
    mode: single
    trigger:
      - platform: time
        at: "20:15:00"
    condition: []
    action:
      - service: light.turn_on
        metadata: {}
        target:
          area_id:
            - patio
        data:
          transition: 5
          kelvin: 2237
          brightness_pct: 60

