automation:

  - id: 'f302181e-c4ea-4549-92b1-972cb39e689b'
    alias: "Game Time | Philadelphia Eagles"
    description: "Game Time: The Philadelphia Eagles are on"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - calendar.philadelphia_eagles
        to: "on"
        id: game_started
      - trigger: state
        entity_id:
          - calendar.philadelphia_eagles
        to: "off"
        id: game_ended
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - game_started
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id:
                    - script.driveway_custom_light_scene
                    - script.firepit_custom_light_scene
                    - script.front_porch_custom_light_scene
                    - script.front_yard_custom_light_scene
                    - script.patio_custom_light_scene
                data:
                  scene: "Special: My scene"
                  repeat_delay:
                    hours: 0
                    minutes: 0
                    seconds: 45
                  onlyonlights: false
                  use_scene_brightness: false
                  brightness: 100
                  my_scene:
                    c:
                      - - 0.217
                        - 0.302
                      - - 0.304
                        - 0.325
                    b: 0.6
          - conditions:
              - condition: trigger
                id:
                  - game_ended
            sequence: []
