automation:

  - id: '02d2b12a-ca52-4b67-901c-b24a760282a1'
    alias: "Game Time | Penn St Nittany Lions"
    description: "Game Time: Penn St Nittany Lions are on"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - calendar.penn_state_nittany_lions_football
        to: "on"
        id: game_started
      - trigger: state
        entity_id:
          - calendar.penn_state_nittany_lions_football
        to: "off"
        id: game_ended
    conditions: []
    actions:
      - choose:
          
          - conditions:
              - condition: trigger
                id:
                  - game_started
            sequence:
              - action: script.turn_on
                metadata: {}
                target:
                  entity_id:
                    - script.driveway_custom_light_scene
                    - script.firepit_custom_light_scene
                    - script.front_porch_custom_light_scene
                    - script.front_yard_custom_light_scene
                    - script.patio_custom_light_scene
                data: &data
                  variables:
                    scene: "Special: My scene"
                    repeat_delay:
                      hours: 0
                      minutes: 0
                      seconds: 45
                    onlyonlights: false
                    use_scene_brightness: false
                    brightness: 100
                    my_scene:
                      c:
                        - - 0.18
                          - 0.175
                        - - 0.304
                          - 0.325
                      b: 0.6

              - condition: or
                conditions:
                  - condition: state
                    entity_id: binary_sensor.winter
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.christmas_eve
                    state: "on"
                  - condition: state
                    entity_id: binary_sensor.christmas_day
                    state: "on"

              - action: script.turn_on
                metadata: {}
                target:
                  entity_id:
                    - script.front_yard_holiday_custom_light_scene
                data: *data
          
          - conditions:
              - condition: trigger
                id:
                  - game_ended
            sequence: 
              - service: input_boolean.turn_on
                target:
                  entity_id:
                    - input_boolean.light_reset
