automation:
  - id: 'b7d8f59b-f3b2-4ddb-973e-76c474bff574'
    alias: "The girls are away"
    description: "Turn off the bathroom lights when the girls are away"
    mode: single
    initial_state: true
    trigger:
      platform: state
      entity_id: group.girls
      from: "home"
      to: "not_home"
      for:
        minutes: 5
    condition: []
    action:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          area_id: bathroom

  - id: '673495f1-92b3-41f8-a363-b55b95034589'
    alias: 'The Girls have left or arrived at a zone'
    description: ''
    mode: single
    trigger:
      - platform: state
        entity_id:
          - person.camdyn_frey
          - person.molly_frey
    condition:
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
    action:
      - service: notify.mobile_app_pixel_8_pro
        data:
          message: clear_notification
          data:
            tag: location
      - service: notify.mobile_app_pixel_8_pro
        metadata: {}
        data_template:
          title: "{{ trigger.to_state.attributes.friendly_name }} is on the Move at {{ states.sensor.time.state }}"
          message: >
            {{ trigger.to_state.attributes.friendly_name }}
            {% if trigger.to_state.state == 'not_home' %}has left {{trigger.from_state.state }} 
            {% else %}arrived at {{ trigger.to_state.state }}
            {% endif %}
          data:
            tag: location
