automation:
  - id: '673495f1-92b3-41f8-a363-b55b95034589'
    alias: 'Notification | People | The Girls are on the move'
    description: 'The Girls have left or arrived at a zone'
    mode: queued
    max: 10
    trigger:
      - platform: state
        entity_id:
          - person.camdyn_frey
          - person.molly_frey
    condition:
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
    action:
      # - service: notify.parent_devices
      #   data:
      #     message: clear_notification
      #     data:
      #       tag: location
      - service: notify.parent_devices
        metadata: {}
        data_template:
          title: "{{ trigger.to_state.attributes.friendly_name }} is on the Move"
          message: >
            {{ trigger.to_state.attributes.friendly_name }}
            {% if trigger.to_state.state == 'not_home' %}has left {{trigger.from_state.state }} 
            {% else %}arrived at {{ trigger.to_state.state }}
            {% endif %}
          data:
            tag: location
