automation:

  - id: 'a63879a8-3229-47fb-a7b5-30b640e7c07a'
    alias: 'Notification | Utility | Sump Pump Offline'
    description: "Notify Parent Devices when the Sump Pump is online or offline"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - switch.basement_sump_pump
        to: unavailable
    conditions: []
    actions:
      - action: notify.parent_devices
        metadata: {}
        data_template:
          title: Sump Pump Offline
          message: >
            The Sump Pump is offline. Check the GFI Outlet!
          data:
            tag: utility

  - id: '0bf71b7a-c2eb-4cc4-a537-250a5ebba41a'
    alias: 'Notification | Utility | Sump Pump Running'
    description: "Notify Parent Devices when the Sump Pump is running"
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.basement_sump_pump_power
        above: 2
    conditions: []
    actions:
      - action: notify.parent_devices
        metadata: {}
        data_template:
          title: Sump Pump Running
          message: >
            The Sump Pump is running
          data:
            tag: utility
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.sump_pump_triggered

  - id: 'afe14c2e-4225-4580-9f99-2889b8ca1eb9'
    alias: 'Notification | Utility | Sump Pump Stopped'
    description: "Notify Parent Devices when the Sump Pump has finished"
    mode: single
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.basement_sump_pump_power
        below: 1
        for:
          minutes: 1
    conditions:
      - condition: state
        entity_id: input_boolean.sump_pump_triggered
        state: "on"
    actions:
      - action: notify.parent_devices
        metadata: {}
        data_template:
          title: Sump Pump Finished
          message: >
            The Sump Pump has finished running
          data:
            tag: utility
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.sump_pump_triggered